USE [SUPERMERCADO]
-- ================================================
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		JHON CAICEDO	
-- Create date: 16-12-2019
-- Description:	Creacion de tablas y relaciones 
-- producto
-- factura
-- =============================================

CREATE TABLE PRODUCTO
(
	ID_PRODUCTO INT NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(30) NULL,
	VALOR_VENTA_PRODUCTO FLOAT NULL,
	CANTIDAD_PRODUCTO INT NULL

	CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
	CONSTRAINT CK_ID_PRODUCTO CHECK (ID_PRODUCTO > 0),
	CONSTRAINT CK_VENTA_PRODUCTO CHECK (VALOR_VENTA_PRODUCTO > 0),
	CONSTRAINT CK_CANTIDAD_PRODUCTO CHECK (CANTIDAD_PRODUCTO > 0)
)

CREATE TABLE FACTURA
(
	ID_FACTURA INT NOT NULL,
	FECHA_FACTURA DATE NULL,
	ID_CLIENTE_FACTURA INT NULL,
	ID_EMPLEADO_FACTURA INT NULL,

	CONSTRAINT PK_ID_FACTURA PRIMARY KEY (ID_FACTURA),
	CONSTRAINT CK_ID_FACTURA CHECK (ID_FACTURA > 0)
)


CREATE TABLE FACTURA_PRODUCTO
(
	ID_FACTURA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD_PRODUCTO INT NULL,

	CONSTRAINT PK_ID_FACTURA_ID_PRODUCTO PRIMARY KEY (ID_FACTURA,ID_PRODUCTO),
	CONSTRAINT CK_CANTIDAD_PRODUCTOS CHECK (CANTIDAD_PRODUCTO > 0)
)


