USE [SUPERMERCADO]
-- ================================================
SET ANSI_NULLS ON
GO
-- =============================================
-- Author:		JHON CAICEDO	
-- Create date: 16-12-2019
-- Description:	Creacion de tablas y relaciones 
-- personas
-- cliente
-- usuario
-- =============================================

CREATE TABLE PERSONA
(
	ID_PERSONA INT  NOT NULL,
	PRIMER_NOMBRE_PERSONA VARCHAR(20) NULL,
	SEGUNDO_NOMBRE_PERSONA VARCHAR(20) NULL,
	PRIMER_APELLIDO_PERSONA VARCHAR(20) NULL,
	SEGUNDO_APELLIDO_PERSONA VARCHAR(20) NULL,
	NUMERO_IDENTIDAD_PERSONA VARCHAR(20) NULL,
	DIRECCION_RESIDENCIA_PERSONA TEXT NULL,
	CORREO_ELECTRONICO_PERSONA TEXT NULL

	CONSTRAINT PK_ID_PERSONA PRIMARY KEY (ID_PERSONA),
	CONSTRAINT UQ_NUMERO_IDENTIDAD_PERSONA UNIQUE (NUMERO_IDENTIDAD_PERSONA),
	CONSTRAINT CK_ID_PERSONA CHECK (ID_PERSONA > 0)
)

CREATE TABLE CLIENTE
(
	ID_CLIENTE INT NOT NULL,
	ID_PERSONA_CLIENTE INT NULL,

	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT UQ_ID_PERSONA_CLIENTE UNIQUE (ID_PERSONA_CLIENTE),
	CONSTRAINT CK_ID_CLIENTE CHECK (ID_CLIENTE > 0)
)

CREATE TABLE USUARIO
(
	ID_USUARIO INT NOT NULL,
	NOMBRE_USUARIO VARCHAR(20) NOT NULL,
	CONTRASENA_USUARIO VARBINARY(100) NOT NULL

	CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO),
	CONSTRAINT UQ_ID_NOMBRE_USUARIO UNIQUE (NOMBRE_USUARIO)
)