USE [SUPERMERCADO]
GO

/****** Object:  StoredProcedure [dbo].[SP_USUARIOS_VALIDAR_CONTRASEÑA]    Script Date: 17/12/2019 07:56:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		JHON CAICEDO	
-- Create date: 16-12-2019
-- Description:	DESENCRIPTA LAS CLAVES DE LOS USUARIOS
-- =============================================
CREATE PROCEDURE [dbo].[SP_BUSCAR_CLIENTE]
	@NUMERO_IDENTIDAD_PERSONA_CLIENTE VARCHAR(20)
AS
BEGIN
	DECLARE @ID_CLIENTE INT

	SELECT 
		@ID_CLIENTE = [SUPERMERCADO].[dbo].[CLIENTE].[ID_CLIENTE]
	FROM 
		[SUPERMERCADO].[dbo].[CLIENTE]
	INNER JOIN 
		[SUPERMERCADO].[dbo].[PERSONA] ON 
			[SUPERMERCADO].[dbo].[CLIENTE].[ID_PERSONA_CLIENTE] = [SUPERMERCADO].[dbo].[PERSONA].[ID_PERSONA]
	WHERE	
		@NUMERO_IDENTIDAD_PERSONA_CLIENTE = [SUPERMERCADO].[dbo].[PERSONA].[NUMERO_IDENTIDAD_PERSONA]

	IF(@ID_CLIENTE > 0)
		RETURN (1)
	ELSE
		RETURN (0)
END
GO


