USE [SUPERMERCADO]
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:	JHON CAICEDO		
-- Create date: 16-12-2019	
-- Description:	ENCRIPTA LAS CLAVES DEL USUARIO
-- =============================================
CREATE PROCEDURE SP_USUARIOS_ENCRIPTACION
	@NOMBRE_USUARIO VARCHAR(20),
	@CLAVE_USUARIO VARCHAR(10)
AS
BEGIN

	--ENCRIPTANDO CLAVE
	DECLARE @CLAVE_ENCRIPTADA VARBINARY(80)

	OPEN SYMMETRIC KEY LLAVE_USUARIOS
	DECRYPTION BY CERTIFICATE cert_LLAVE_USUARIOS
				
		SET @CLAVE_ENCRIPTADA = EncryptByKey(Key_GUID('LLAVE_USUARIOS') , @CLAVE_USUARIO)
				
	CLOSE SYMMETRIC KEY LLAVE_USUARIOS

	--INGRESANDO EL NUEVO USUARIO
	INSERT INTO	
		[SUPERMERCADO].[dbo].[USUARIO]
		(
			[SUPERMERCADO].[dbo].[USUARIO].[NOMBRE_USUARIO],
			[SUPERMERCADO].[dbo].[USUARIO].[CONTRASENA_USUARIO]
		)
	VALUES 
		(
			@NOMBRE_USUARIO,
			@CLAVE_ENCRIPTADA
		)


END
GO