USE [SUPERMERCADO]
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		JHON CAICEDO	
-- Create date: 16-12-2019
-- Description:	DESENCRIPTA LAS CLAVES DE LOS USUARIOS
-- =============================================
CREATE PROCEDURE SP_USUARIOS_DESENCRIPTACION
	@ID_USUARIO INT 
AS
BEGIN
	
	DECLARE @CLAVE_ENCRIPTADA VARBINARY(100)
	DECLARE @CLAVE_DESENCRIPTADA VARCHAR(10)

	--BUSCANDO LA CLAVE
	SELECT
		@CLAVE_ENCRIPTADA = [SUPERMERCADO].[dbo].[USUARIO].[CONTRASENA_USUARIO]
	
	FROM 
		[SUPERMERCADO].[dbo].[USUARIO]

	WHERE	
		@ID_USUARIO = [SUPERMERCADO].[dbo].[USUARIO].[ID_USUARIO]


	--DESENCRIPTANDO CLAVE
	OPEN SYMMETRIC KEY LLAVE_USUARIOS
	DECRYPTION BY CERTIFICATE cert_LLAVE_USUARIOS
		
		SET @CLAVE_DESENCRIPTADA =
			CAST(DecryptByKey(@CLAVE_ENCRIPTADA) AS VARCHAR(10))
		
	CLOSE SYMMETRIC KEY LLAVE_USUARIOS

	RETURN (@CLAVE_DESENCRIPTADA)

END
GO