USE [SUPERMERCADO]
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		JHON CAICEDO	
-- Create date: 16-12-2019
-- Description:	DESENCRIPTA LAS CLAVES DE LOS USUARIOS
-- =============================================
CREATE PROCEDURE SP_USUARIOS_VALIDAR_CONTRASEÑA
	@NOMBRE_USUARIO VARCHAR(20),
	@CONTRASENA_USUARIO VARCHAR(10)
AS
BEGIN
	DECLARE @ID_USUARIO INT

	SELECT 
		@ID_USUARIO = [SUPERMERCADO].[dbo].[USUARIO].[ID_USUARIO]
	FROM 
		[SUPERMERCADO].[dbo].[USUARIO]
	WHERE	
		@NOMBRE_USUARIO = [SUPERMERCADO].[dbo].[USUARIO].[NOMBRE_USUARIO]
	
	DECLARE @CLAVE_ENCRIPTADA VARBINARY(100)
	DECLARE @CLAVE_DESENCRIPTADA VARCHAR(10)

	--BUSCANDO LA CLAVE
	SELECT
		@CLAVE_ENCRIPTADA = [SUPERMERCADO].[dbo].[USUARIO].[CONTRASENA_USUARIO]
	
	FROM 
		[SUPERMERCADO].[dbo].[USUARIO]

	WHERE	
		@ID_USUARIO = [SUPERMERCADO].[dbo].[USUARIO].[ID_USUARIO]


	--DESENCRIPTANDO CLAVE
	OPEN SYMMETRIC KEY LLAVE_USUARIOS
	DECRYPTION BY CERTIFICATE cert_LLAVE_USUARIOS
		
		SET @CLAVE_DESENCRIPTADA =
			CAST(DecryptByKey(@CLAVE_ENCRIPTADA) AS VARCHAR(10))
		
	CLOSE SYMMETRIC KEY LLAVE_USUARIOS

	IF(@CONTRASENA_USUARIO = @CLAVE_DESENCRIPTADA)
		RETURN (1)
	ELSE
		RETURN (0)
END
GO