//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int ID_PERSONA { get; set; }
        public string PRIMER_NOMBRE_PERSONA { get; set; }
        public string SEGUNDO_NOMBRE_PERSONA { get; set; }
        public string PRIMER_APELLIDO_PERSONA { get; set; }
        public string SEGUNDO_APELLIDO_PERSONA { get; set; }
        public string NUMERO_IDENTIDAD_PERSONA { get; set; }
        public string DIRECCION_RESIDENCIA_PERSONA { get; set; }
        public string CORREO_ELECTRONICO_PERSONA { get; set; }
    }
}
