USE [SUPERMERCADO]
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTOR: JHON CAICEDO
-- FECHA DE CREACION: 17/12/2019
-- DESCRIPCION: CALCULA EL TOTAL A PAGAR DE UNA FACTURA
-- =============================================
CREATE FUNCTION [dbo].[TOTAL_FACTURA]
(
	@ID_FACTURA INT
)
RETURNS FLOAT
AS
BEGIN
	
	DECLARE @TOTAL FLOAT = 0

	SELECT 
		@TOTAL = @TOTAL +
				[SUPERMERCADO].[dbo].[FACTURA_PRODUCTO].[CANTIDAD_PRODUCTO] *
				[SUPERMERCADO].[dbo].[PRODUCTO].[VALOR_VENTA_PRODUCTO]
	FROM 
		[SUPERMERCADO].[dbo].[FACTURA_PRODUCTO]
	
	INNER JOIN 
		[SUPERMERCADO].[dbo].[FACTURA]
	ON
		[SUPERMERCADO].[dbo].[FACTURA].[ID_FACTURA] =
		[SUPERMERCADO].[dbo].[FACTURA_PRODUCTO].[ID_FACTURA]
	
	INNER JOIN 
		[SUPERMERCADO].[dbo].[PRODUCTO]
	ON
		[SUPERMERCADO].[dbo].[PRODUCTO].[ID_PRODUCTO] =
		[SUPERMERCADO].[dbo].[FACTURA_PRODUCTO].[ID_PRODUCTO]
		
	WHERE 
		@ID_FACTURA = [SUPERMERCADO].[dbo].[FACTURA].[ID_FACTURA]
				
				

	RETURN @TOTAL

END
GO